- name: "Update the system"
  yum:
    name: '*'
    state: latest
  become: yes
  tags:
    - system

- name: "Download java rpm package ..."
  get_url:
    url: "{{ java_rpm_repo }}"
    dest: /tmp
    validate_certs: no
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
  become: yes 

- name: Install Java in the machine
  yum:
    name: "/tmp/{{ java_rpm_repo | urlsplit('path') | basename }}"
    state: present
  become: yes

  
